### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mcheung-nhs**
## Description
Update dependencies to fix an issue with sass and latest version of node

## Checklist

- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Follows our [coding standards and style guide](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] CHANGELOG entry

### CODE REVIEW

**Review by DomBaker — APPROVED** [review]
LGTM

**Comment by andymantell** [comment]
I get this message:

```
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
```

and am then left with a dirty lockfile, going from version 1 to 2. Was the lockfile in this pull request created with node 16 / npm 8?

I do think we should be validating which version of node people are using with this repo. Shall I add it in to this pull request?

Or we can just rebuild the lockfile - i.e. actually delete it and let npm 8 create a new one fresh.

**Comment by andymantell** [comment]
Also, looks like the package version is updated from 6.0.1 to 6.0.2 - I don't know if this is necessary? This doesn't actually change anything in the npm package and so wouldn't need a release of it's own.

**Comment by mcheung-nhs** [comment]
Hi @andymantell - I've generated a new package-lock for node 16 / npm 8 and reverted the package version.

**Review by andymantell — APPROVED** [review]
This looks great. I ran `npm install` at my end and the package-lock remained clean, so I think we're in a good place now.

As mentioned earlier on the call - we need to be mindful of what package-lock changes other contributors might make, especially if they are using different versions of npm. If a pull request comes in - it generally _shouldn't_ include any package-lock changes, unless someone has actually changed the packages that are installed. As obvious as that sounds!

**Comment by andymantell** [comment]
@DomBaker This one is good to go I reckon. Should unblock the other pull requests' build pipelines once it's merged.

**Pull request merged**
