### PR TITLE
Draft: Adding an 'account' section to header

### PR DESCRIPTION
**Pull request by frankieroberto**
## Description

This section would allow you to add 'account' related items at the top-right of the header, like this:

Screenshot 2024-07-10 at 14 18 44

The items can be either links (if an `href` is present) or just text or HTML, in order to allow for maximum flexibility.

Resolves https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/192

## Checklist

- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Follows our [coding standards and style guide](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] CHANGELOG entry

### CODE REVIEW

**Comment by frankieroberto** [comment]
Our current thinking is to basically allow the account items to stack on the right on mobile at the point where they no longer fit.  

The service name could also wrap onto 2 or more lines if needed, but remaining to the right of the logo instead of dropping beneath it.

Example here (spacing is all a bit rough still):

Screenshot 2024-07-16 at 09 20 17

**Comment by Tosin-Balogun** [comment]
@frankieroberto this is wicked, I saw this from the slack thread around headers. Do you have a prototype hosted anywhere we can inspect?

**Comment by chrimesdev** [comment]
LGTM this would be useful on Screening & happy to test in our service.

**Comment by frankieroberto** [comment]
> @frankieroberto this is wicked, I saw this from the slack thread around headers. Do you have a prototype hosted anywhere we can inspect?

@Tosin-Balogun Not yet - although if you clone this repo and checkout this branch and then run `npm start` you can see some working examples!

> LGTM this would be useful on Screening & happy to test in our service.

@chrimesdev we’re not quite there yet, but hopefully soon!

**Comment by paulrobertlloyd** [comment]
Replaced with #1063.

**Pull request closed without merging**
