### PR TITLE
Update actions/checkout workflow to v4

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
## Description

Updates to latest version as using v2 now shows a depreciation message.

## Checklist

- [x] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [x] Follows our [coding standards and style guide](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] CHANGELOG entry

### CODE REVIEW

**Review by frankieroberto — APPROVED** [review]

**Comment by frankieroberto** [comment]
@paulrobertlloyd good catch! Could also set up Dependabot to keep these updated automatically.

**Comment by paulrobertlloyd** [comment]
Yeah; you want to add that to the dependabot workflow config?

**Comment by frankieroberto** [comment]
@paulrobertlloyd there isn’t one! (yet)

**Comment by paulrobertlloyd** [comment]
Oh yeah; how is Dependabot working then?

**Comment by frankieroberto** [comment]
@paulrobertlloyd dunno, some kind of default? 🤷‍♂️

**Pull request merged**
