### PR TITLE
Ensure error summary receives focus on render.

### LINKED ISSUE #702: Error summary doesn't receive keyboard focus when rendered
When a form has validation errors, and the error summary is shown I expected it to receive keyboard focus(otherwise why has it got a `tabindex="-1"` but it's not. I believe this to be the reason why the GDS error summary has focus attached [via JavaScript](https://github.com/alphagov/govuk-frontend/blob/803da2c92d1a73401ac506b2dc8a393fae940508/src/govuk/components/error-summary/error-summary.js#L14).

I'm happy to contribute a PR to address this if it needs a similar fix to the GDS one 😄

### PR DESCRIPTION
**Pull request by damian**
## Description
- Ensure error summary receives focus on render. Fixes #702.

## Checklist

- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Follows our [coding standards and style guide](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] CHANGELOG entry

### CODE REVIEW

**Comment by AdamChrimes** [comment]
Hey @damian thanks for this, looks good. Do we need the Error summary links events adding too?

cc: @tomdoughty @andymantell

**Comment by andymantell** [comment]
I think we should have the link events too. Could we more directly lift the code from upstream in govuk-frontend? The comments against the code in there around the click events on the error summary links make it sound worth having:

https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/error-summary/error-summary.js

Are there any reasons _not_ to simply copy this entire file in? (And just tweak the way it's invoked to match the nhsuk-frontend pattern)

**Comment by AdamChrimes** [comment]
Hey @damian please could you rebase this `master` and I will merge it? We can iterate on this, following the above comments, in the near future.

Thanks again for this!

**Comment by andymantell** [comment]
I've manually folded this into my current form validation work on 111 online and it's working nicely for me. 👍🏻

**Review by tomdoughty — COMMENTED** [review]
LGTM 👍

**Pull request merged**
