### PR TITLE
[refs #676] Move icons using background into ::before to simplify automated testing

### PR DESCRIPTION
**Pull request by stevenwaterman**
## Description
Resolving https://github.com/nhsuk/nhsuk-frontend/issues/676 - this updates the expander and breadcrumb components to prevent aXe from seeing accessibility violations due to the use of background images on elements that contain text. This fixes the `elements must have sufficient color contrast` warning.

They look pixel-perfect identical across all resolutions.

Screenshot 2021-03-16 at 11 19 19

Screenshot 2021-03-16 at 11 19 28

## Checklist

- [x] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [x] Follows our [coding standards and style guide](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [x] CHANGELOG entry

### CODE REVIEW

**Comment by stevenwaterman** [comment]
Not really sure how to interpret the CI failures - happy to try and fix it if you can explain what it's checking and what's going wrong

**Comment by AdamChrimes** [comment]
Hi @stevenwaterman thanks for having a look at this.

The test that is failing is our [visual regression testing using BackstopJS](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/automated-testing.md#visual-regression-testing---backstopjs) tests. 

After running the tests locally it looks like the test is failing because the Breadcrumb back icon ([Reference to the change](https://github.com/nhsuk/nhsuk-frontend/pull/718/files#diff-271343e0b3d37e3308fe1dcddf58d715ad265819b2104e1758c9fd89eaa4ea0aR92)) has been cut off on breakpoints lower than tablet (see screenshots attached)

beadcrumb-before
breadcrumb-after

**Comment by stevenwaterman** [comment]
Visual regression tests are awesome, glad you have them set up here. Was a classic case of forgetting to test one scenario at mobile resolution (on a bit of code I wrote 3 months ago 😆 ). Should all be fixed now, will wait for the CI to re-run.

**Comment by AdamChrimes** [comment]
Thanks @stevenwaterman thats sorted it! Everything seems to be OK, I'll just do some manual testing in the morning and we can look at getting this merged.

Thanks again for picking this up.

**Comment by AdamChrimes** [comment]
Hi @stevenwaterman sorry for the delay - few coronavirus related projects came in. 

All seems OK now and works on browsers I've checked - if you could just rebase with `master` to resolve the `CHANGELOG` conflict we can get this merged.

**Review by AdamChrimes — APPROVED** [review]

**Comment by AdamChrimes** [comment]
Thanks again for this @stevenwaterman

**Pull request merged**
