### PR TITLE
Remove support for IE8-10

### PR DESCRIPTION
**Pull request by mcheung-nhs**
## Checklist

- [x] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [x] Follows our [coding standards and style guide](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [x] CHANGELOG entry

### CODE REVIEW

**Comment by AdamChrimes** [comment]
Looks good to me, I wonder if its worth linking to the [GOV.UK - changing our testing requirements for Internet Explorer 8, 9 and 10 blog post](https://technology.blog.gov.uk/2018/06/26/changing-our-testing-requirements-for-internet-explorer-8-9-and-10/) in the CHANGELOG and the browser support & testing markdown files for future reference?

**Comment by AdamChrimes** [comment]
I've pushed some commits to remove references to internet explorer in some of the Sass comments and also removed the `ie.scss` partial, which contained `display: block;` fixes for IE8 and IE9.

**Comment by mcheung-nhs** [comment]
Thanks @AdamChrimes. I've updated the version number and added the gov.uk blog entry link. Can you check that the wording sounds OK.

**Comment by AdamChrimes** [comment]
Looks good to me, @tomdoughty has also refactored IE related JavaScript https://github.com/nhsuk/nhsuk-frontend/pull/681

I think we're going to release v4.1.0 first, then release this with our next breaking change release. We've got a couple of other breaking changes to go in with this so probably easier to batch them together.

I'll merge this in and update the `CHANGELOG` once we've released 4.1.0. Cheers Michael!

**Comment by AdamChrimes** [comment]
Hey @mcheung-nhs this just needs rebasing with master and conflicts resolving. We'll also need to split out the `CHANGELOG` into its own entry under 5.0.0

**Comment by mcheung-nhs** [comment]
@AdamChrimes - merged and updated `CHANGELOG`

**Comment by mcheung-nhs** [comment]
Created a 'cleaner' PR - https://github.com/nhsuk/nhsuk-frontend/pull/696 so closing this now

**Pull request closed without merging**
