### PR TITLE
Feature/character count

### PR DESCRIPTION
**Pull request by andymantell**
## Description

Character count component, directly ported from the govuk-frontend version. Only changes are to rename govuk -> nhsuk and fix the JS to comply with this repo's linting rules.

Associated design backlog item here https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/172 - several instances of people asking for this functionality. I think it would be good to get this in and stop people reinventing the wheel.

We've been using a home-grown one on 111 online. I would like to replace it with something that is better tested and has had more thought put into it with regards to accessibility. The govuk-frontend one meets this criteria better than ours.

## Checklist

- [x] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [X] Follows our [coding standards and style guide](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [x] CHANGELOG entry

### CODE REVIEW

**Comment by andymantell** [comment]
Pending testing as part of some work we're doing on 111 online. I'll revisit this in a couple of weeks to check that checkbox...

**Comment by Fenwick17** [comment]
Markup, JS and CSS all looks good. I'll get some device/screen reader testing done

**Comment by andymantell** [comment]
Looks like there's a bit of a refactor going on over here:

https://github.com/alphagov/govuk-frontend/pull/2577

I think perhaps we should put this on hold until that's merged. It seems to be fairly far along so we may as well wait and get the improved version in.

**Comment by chrimesdev** [comment]
We're looking at including this in a service, will test this out for you!

**Comment by andymantell** [comment]
This has now been incorporated into 111 online and has been cross browser tested, as well as with various bits of assistive tech.

**Review by wa-rren-dev — CHANGES_REQUESTED** [review]
tiny wording then 👍👍👍

**Comment by wa-rren-dev** [comment]
> This has now been incorporated into 111 online and has been cross browser tested, as well as with various bits of assistive tech.

Great cheers @andymantell. I'll carry this forward but we might need a bit more detail about the testing that was done when preparing it for the Service Manual.

**Pull request merged**
