### PR TITLE
remove deprecated uses of SASS division operator via sass-migrator

### PR DESCRIPTION
**Pull request by britannio**
## Description
Closes https://github.com/nhsuk/nhsuk-frontend/issues/752

## Checklist

- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Follows our [coding standards and style guide](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] CHANGELOG entry

### CODE REVIEW

**Comment by chrimesdev** [comment]
Hey @britannio thanks for opening this pull request and sorry for the delay in the response, we've had a bit of annual leave and people moving around within the team recently.

I will take a look at this sometime this week.

**Comment by chrimesdev** [comment]
Hey @britannio this all looks good, are you to OK to bump the `package.json` and `package-json.lock` versions to `5.1.1` and add a new entry to the [CHANGELOG](https://github.com/nhsuk/nhsuk-frontend/blob/master/CHANGELOG.md) under the heading `5.1.1 - Unreleased`?

**Comment by chrimesdev** [comment]
We may need to review the impact on projects still using compilers (eg. Ruby Sass, Dart Sass and Ruby Sass) before we progress any further than this. The support for those compilers is still non existent so we have to weigh up the trade off between a modern compiler giving a warning about very recently deprecated functionality compared to breaking some compilers all together.

**Comment by britannio** [comment]
> Hey @britannio this all looks good, are you to OK to bump the `package.json` and `package-lock.json` versions to `6.0.0` and add a new entry to the [CHANGELOG](https://github.com/nhsuk/nhsuk-frontend/blob/master/CHANGELOG.md) under the heading `6.0.0 - Unreleased`?

Done!

**Comment by britannio** [comment]
@chrimesdev Anything else I need to do here?

**Comment by chrimesdev** [comment]
Hey @britannio see my comment above, this will be quite a big breaking change for people using other compilers. I'm not sure we are quite ready to make the switch.

**Comment by kevinkuszyk** [comment]
@chrimesdev are you still considering this for a v6 release?  And if so, do you have a timeframe for that?

We're seeing lots of noise in the CI since we upgraded to the latest sass.  Whilst I agree you don't want to break other consumers of the lib, major version bumps are always the time to do it.

**Comment by diroussel** [comment]
This would be a great change to have, as node-sass has some security issues, and switching to latest sass would fix this.  But in tryin the switch, I hit this error.

Sass 1.33 is now 5 months old, so this would be a reasonable time to make the upgrade.  If people don't want to upgrade, they can just not upgrade to the lastest nhsuk-frontend for a while.

**Comment by wa-rren-dev** [comment]
Closing this as we're updating the version of sass required in our [v7 alpha](https://github.com/nhsuk/nhsuk-frontend/pull/831)

**Pull request closed without merging**
