### PR TITLE
Update header menu links

### PR DESCRIPTION
**Pull request by henocookie**
## Description
Update the header menu navigation links to reflect the current links on https://www.nhs.uk/

## Checklist

- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Follows our [coding standards and style guide](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] CHANGELOG entry - n/a

### CODE REVIEW

**Comment by chrimesdev** [comment]
Thanks for this @henocookie, do you think you will be able to do the same on the [NHS digital service manual Header examples](https://service-manual.nhs.uk/design-system/components/header)?

I'll fix the broken pipeline and get this merged - but would be good if they both matched.

**Comment by henocookie** [comment]
> Thanks for this @henocookie, do you think you will be able to do the same on the [NHS digital service manual Header examples](https://service-manual.nhs.uk/design-system/components/header)?
> 
> I'll fix the broken pipeline and get this merged - but would be good if they both matched.

Of course! I forgot the service manual header had changed too, so will update those examples.

**Comment by henocookie** [comment]
Just realised this PR doesn't include the update exposed search on mobile that the I.A. team recently implemented. Would @bencullimore be able to update the code to include this? 😀

**Comment by bencullimore** [comment]
> Just realised this PR doesn't include the update exposed search on mobile that the I.A. team recently implemented. Would @bencullimore be able to update the code to include this? 😀

@pflynny will be able to help Henry.

**Comment by chrimesdev** [comment]
The change to the Header component to expose the Search on mobile may be out of scope for this Pull request, but it definitely needs looking at.

**Comment by chrimesdev** [comment]
After speaking to the IA team, we're going to delay adding the exposed search to the frontend library until we have more user research from using it outside of the NHS website. So we can go ahead with updating just the Header links.

**Comment by DomBaker** [comment]
Updated the BackstopJS Test Bitmap References - Ready to Merge @chrimesdev

**Review by DomBaker — COMMENTED** [review]
Reviewed and approved

**Review by DomBaker — APPROVED** [review]

**Pull request merged**
