### PR TITLE
Fix for label backstop test and apostrophe standardisation 

### PR DESCRIPTION
**Pull request by xLasercut**
## Checklist

- [ ] SCSS
- [ ] Nunjucks macro
- [ ] A standalone example
- [ ] README/Documentation with HTML snippet
- [x] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [x] Visual tests ([BackstopJS](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/automated-testing.md))
- [ ] Print stylesheet considered
- [x] CHANGELOG entry

### CODE REVIEW

**Comment by AdamChrimes** [comment]
I remember there being a discussion for straight `'` vs curly `’` apostrophe when used in content, I think curly ones are the correct ones to use in content. I'll see if I can find the relevant messages.

**Comment by AdamChrimes** [comment]
See the discussion on this PR: https://github.com/nhsuk/redesign-frontend-kit/pull/331

**Comment by xLasercut** [comment]
Reverted apostrophe change.

**Comment by AdamChrimes** [comment]
Needs the date changing to 'Unreleased' in the CHANGELOG until its release.

**Pull request merged**
