### PR TITLE
Ensure logo-nhs.svg is a valid SVG file.

### PR DESCRIPTION
**Pull request by codebymikey**
Add the xlink namespace to address the 'Unbound namespace prefix: "xlink"' error.

## Description
The SVG is currently not valid.

## Checklist

- [x] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [x] Follows our [coding standards and style guide](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] CHANGELOG entry

### CODE REVIEW

**Comment by AdamChrimes** [comment]
Hey @codebymikey thanks for opening this pull request.

Do you have a bit more information about the error you were getting so I can understand the context of this change? Where  are you getting the `'Unbound namespace prefix: "xlink"' error`?

We are aware of some issues affecting HTML validation with the fallback png logo (https://github.com/nhsuk/nhsuk-frontend/issues/572) but this doesn't seem to be related.

**Comment by codebymikey** [comment]
I just noticed that the file wasn't valid in general (none of the svg viewers I found online could open it), see Github's own SVG preview breaking:
https://github.com/nhsuk/nhsuk-frontend/blob/e3850ef/packages/assets/logos/logo-nhs.svg
vs
https://github.com/nhsuk/nhsuk-frontend/blob/28c9253/packages/assets/logos/logo-nhs.svg

Viewing the [svg](https://raw.githubusercontent.com/nhsuk/nhsuk-frontend/e3850ef9cfffb23d3b6f241175e45e566f7cc50d/packages/assets/logos/logo-nhs.svg) directly in Chrome spits out an error message regarding the namespace prefix, but still manages to render.

The error I referenced in particular was coming from running the assets through [gulp-image](https://www.npmjs.com/package/gulp-image)'s [svgo ](https://www.npmjs.com/package/svgo) optimizer which apparently uses `sax-js` under the hood:

https://github.com/isaacs/sax-js/blob/5aee2163d55cff24b817bbf550bac44841f9df45/lib/sax.js#L809-L813

**Comment by AdamChrimes** [comment]
Thanks @codebymikey that makes sense - I'm surprised we haven't spotted this before!

The change looks good but there are a couple of other places that we'll need to make this change; 

Header component template file (Line 17) https://github.com/nhsuk/nhsuk-frontend/blob/master/packages/components/header/template.njk#L17

Header component template file (Line 28) https://github.com/nhsuk/nhsuk-frontend/blob/master/packages/components/header/template.njk#L28

Header component README file (There are a couple of places here) https://github.com/nhsuk/nhsuk-frontend/blob/master/packages/components/header/README.md

We'll need a `CHANGELOG` entry too under `4.0.1` as a fix - though we can pick this up if you prefer.

Thanks again.

**Comment by codebymikey** [comment]
Applied the namespace to all known instances of `xlink` in the codebase.

I'll leave the CHANGELOG part to you guys to handle.

**Review by AdamChrimes — APPROVED** [review]
Thanks @codebymikey looks good, I'll update the `CHANGELOG` before the next release

**Pull request merged**
