### PR TITLE
Cypress tests

### PR DESCRIPTION
**Pull request by suryapulakhandam**
## Checklist

- [ ] SCSS
- [ ] Nunjucks macro
- [ ] A standalone example
- [ ] README/Documentation with HTML snippet
- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Print stylesheet considered
- [ ] CHANGELOG entry

### CODE REVIEW

**Comment by suryapulakhandam** [comment]
Updated the Cypress tests with the change in the class names, and added tests for label component. Additional checks are been added to check some text exists for links, summary, heading, labels, hints

**Comment by suryapulakhandam** [comment]
All, the cypress tests are passed, backstopJS tests are failing due to image issues.

**Comment by AdamChrimes** [comment]
@suryapulakhandam please could update rebase this branch with master.

**Comment by AdamChrimes** [comment]
We're going to pick this piece of work up with the testing implementation along with https://github.com/nhsuk/nhsuk-frontend/pull/387 in a clean branch/PR.

**Pull request closed without merging**
