### PR TITLE
fixes backstop test not working on linux or windows

### PR DESCRIPTION
**Pull request by xLasercut**
## Checklist

- [ ] SCSS
- [ ] Nunjucks macro
- [ ] A standalone example
- [ ] README/Documentation with HTML snippet
- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Visual tests ([BackstopJS](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/automated-testing.md))
- [ ] Print stylesheet considered
- [ ] CHANGELOG entry

Fixes backstop tests failing on linux and windows by adding a script to run `/sbin/ip route` inside the container and retrieve the docker bridge IP.

### CODE REVIEW

**Comment by AdamChrimes** [comment]
@mikemonteith are you OK to have a look at this? Our Travis CI pipeline is Linux so also thought it was working there and I'm sure we had it running on Suryas machine (Windows)

**Comment by mikemonteith** [comment]
@xLasercut can you explain this a bit?
What command are you trying to run?
I think we added the `testhost` argument so that you could pass the correct URL for your specific environment. If we have some code to figure out the ip address, it will need to be tested on a range of hosts.

**Comment by xLasercut** [comment]
@mikemonteith 
The command is `/sbin/ip route`

which will give us the docker bridge ip in the line with:
default via <IP> dev eth0

This will be run inside the container (which will always be linux). https://stackoverflow.com/questions/22944631/how-to-get-the-ip-address-of-the-docker-host-from-inside-a-docker-container

**Comment by AdamChrimes** [comment]
There is no straight forward fix for this, so we're going to close this PR and investigate it further.

**Pull request closed without merging**
